imagePullSecrets: []

replicaCount: 1

ingress:
  enabled: false
  className: ""
  annotations: {}
  tls: []
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix

frontend:
  enabled: true
  image:
    repository: registry.gitlab.com/eagledevstack/moviecat-web
    pullPolicy: IfNotPresent
    tag: "054c7f75"
  type: ClusterIP
  protocol: TCP
  port: 3000
  targetPort: 3000
  volumeMounts: []
  resources: {}

backend:
  image:
    repository: registry.gitlab.com/eagledevstack/moviecat-backend
    pullPolicy: IfNotPresent
    tag: "bb9220cb"
  volumeMounts: []
  resources: {}

postgres:
  image:
    repository: postgres
    pullPolicy: IfNotPresent
    tag: "17"
  volumeMounts: []
  resources: {}

redis:
  image:
    repository: redis
    pullPolicy: IfNotPresent
    tag: "8"
  volumeMounts: []
  resources: {}

secretRef: ""

volumes: []

nodeSelector: {}

tolerations: []

affinity: {}
