{{- if $.Values.frontend.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-deployment" .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ printf "%s-app" .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ printf "%s-app" .Chart.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ printf "%s-frontend" .Chart.Name }}
          image: "{{ $.Values.frontend.image.repository }}:{{ $.Values.frontend.image.tag }}"
          imagePullPolicy: {{ $.Values.frontend.image.pullPolicy }}
          {{- with $.Values.secretRef }}
          envFrom:
            - secretRef:
                name: {{ $.Values.secretRef }}
          {{- end }}
          ports:
            - name: {{ $.Chart.Name }}
              containerPort: {{ .Values.frontend.targetPort }}
              protocol: {{ .Values.frontend.protocol }}
          {{- with .Values.frontend.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.frontend.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - name: {{ printf "%s-backend" .Chart.Name }}
          image: "{{ $.Values.backend.image.repository }}:{{ $.Values.backend.image.tag }}"
          imagePullPolicy: {{ $.Values.backend.image.pullPolicy }}
          {{- with $.Values.secretRef }}
          envFrom:
            - secretRef:
                name: {{ $.Values.secretRef }}
          {{- end }}
          {{- with .Values.backend.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.backend.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - name: {{ printf "%s-db" .Chart.Name }}
          image: "{{ $.Values.postgres.image.repository }}:{{ $.Values.postgres.image.tag }}"
          imagePullPolicy: {{ $.Values.postgres.image.pullPolicy }}
          {{- with $.Values.secretRef }}
          envFrom:
            - secretRef:
                name: {{ $.Values.secretRef }}
          {{- end }}
          {{- with .Values.postgres.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.postgres.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - name: {{ printf "%s-cache" .Chart.Name }}
          image: "{{ $.Values.redis.image.repository }}:{{ $.Values.redis.image.tag }}"
          imagePullPolicy: {{ $.Values.redis.image.pullPolicy }}
          {{- with $.Values.secretRef }}
          envFrom:
            - secretRef:
                name: {{ $.Values.secretRef }}
          {{- end }}
          {{- with .Values.redis.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.redis.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}