{{- if $.Values.frontend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-service" .Chart.Name }}
spec:
  selector:
    app: {{ printf "%s-app" .Chart.Name }}
  type: {{ $.Values.frontend.type }}
  ports:
  - name: {{ .Chart.Name }}
    protocol: {{ $.Values.frontend.protocol }}
    port: {{ $.Values.frontend.port }}
    targetPort: {{ $.Values.frontend.targetPort }}
---
{{- end }}
